<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Agregar Planta</title>
</head>
<body>
    <form action="addPlants" method="POST">
    <label for="nombre">Nombre de la planta:</label>
    <input type="text" id="nombre" name="nombre" required>

    <label for="precio">Precio:</label>
    <input type="number" id="precio" name="precio" required>

    <label for="stock">Stock:</label>
    <input type="number" id="stock" name="stock" required>

    <label for="id_pedido">Pedido al que pertenece:</label>
    <select id="id_pedido" name="id_pedido">
        <?php foreach ($orders as $order): ?>
            <option value="<?= $order->id_pedido; ?>"><?php echo $order->id_pedido; ?></option>
        <?php endforeach; ?>
    </select>
    <button type="submit">Agregar Planta</button>
</form>
<a href="<?php echo BASE_URL; ?>plants">Volver a la lista de plantas</a>
</body>
</html>



