<!-- formulario de alta de tarea -->
<form action="addCategories" method="POST" class="my-4">
    <div class="row">
        <div class="col-9">
            <div class="form-group">
                <label>Fecha Pedido</label>
                <input required name="fecha_pedido" type="date" class="form-control">
            </div>
        </div>

        <div class="col-3">
            <div class="form-group">
                <label>Estado</label>
                <input required name="estado" type="text" class="form-control">
            </div>
        </div>
    </div>

    <div class="form-group">
        <label>Total</label>
        <input type="number" name="total" class="form-control">
    </div>

    <button type="submit" class="btn btn-primary mt-2">Agregar</button>
    
</form>
<?php require_once 'templates/layout/footer.phtml';
