<?php require_once './templates/layout/header.phtml' ?>

    <form action="<?= BASE_URL ?>update" method="POST">
        <input type="hidden" name="id_planta" value="<?= $plant->id_planta ?>">

        <label for="nombre">Nombre de la planta:</label>
        <input type="text" id="nombre" name="nombre" value="<?= $plant->nombre?>" required>
 
        <label for="precio">Precio:</label>
        <input type="number" id="precio" name="precio" value="<?= $plant->precio?>" required>

        <label for="stock">Stock:</label>
        <input type="number" id="stock" name="stock" value="<?= $plant->stock?>" required>

        <label for="id_pedido">Pedido al que pertenece:</label>
        <select id="id_pedido" name="id_pedido">
        <?php foreach ($orders as $order): ?>
            <option value="<?= $order->id_pedido; ?>"><?= $order->estado; ?></option>
        <?php endforeach; ?>
        </select>
        <button class="btn btn-primary" type="submit">Editar Planta</button>
    </form>
    <a href="<?= BASE_URL; ?>home" class="btn btn-success mt-4">Volver a la lista de plantas</a>
    
<?php require_once './templates/layout/footer.phtml'?>