<?php require_once './templates/layout/header.phtml' ?>

    <form action="add" method="POST" enctype="multipart/form-data">
    <label for="nombre">Nombre de la planta:</label>
    <input type="text" id="nombre" name="nombre" required>

    <label for="precio">Precio:</label>
    <input type="number" id="precio" name="precio" required>

    <label for="stock">Stock:</label>
    <input type="number" id="stock" name="stock" required>

    <label for="id_pedido">Pedido al que pertenece:</label>
    <select id="id_pedido" name="id_pedido">
        <?php foreach ($orders as $order): ?>
            <option value="<?= $order->id_pedido; ?>"><?= $order->estado; ?></option>
        <?php endforeach; ?>
    </select>
    <!-- Input para subir la imagen -->
    <label for="imagen">Imagen de la planta:</label>
        <input type="file" id="imagen" name="imagen" required>
    <button type="submit">Agregar Planta</button>
</form>
<a href="<?= BASE_URL; ?>home" class="btn btn-success mt-4">Volver a la lista de plantas</a>

<?php require_once './templates/layout/footer.phtml'?>



