<!DOCTYPE html>
<html lang="es">

<!-- head -->
<head>
    <meta charset="UTF-8">
    <base href="<?php echo BASE_URL ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="stylesheet" href="css/style.css">
    <title>Titulo</title>
</head>
<body>


<!-- formulario de edicion de categorias -->
 <?php var_dump(BASE_URL); ?>
<form action="<?=BASE_URL?>updateCategory" method="POST" class="my-4">
    <div class="row">
    <div class="col-9">
            <div class="form-group">
                <label>ID</label>
                <input  required name="id_pedido" value="<?=$category->id_pedido ?>" type="hidden" class="form-control">
            </div>
        </div>
        <div class="col-9">
            <div class="form-group">
                <label>Fecha Pedido</label>
                <input required name="fecha_pedido" value="<?=$category->fecha_pedido ?>" type="date" class="form-control">
            </div>
        </div>

        <div class="col-3">
            <div class="form-group">
                <label>Estado</label>
                <input required name="estado" value="<?=$category->estado?>" type="text" class="form-control">
            </div>
        </div>
    </div>

    <div class="form-group">
        <label>Total</label>
        <input type="number" name="total" value="<?=$category->total?>" class="form-control">
    </div>

    <button type="submit" class='btn btn-warning btn-sm'>Editar </button>
    
</form>