<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Vivero</title>
</head>
<body>
    <h1>Lista de Plantas</h1>
    <ul>
        <?php foreach ($plants as $plant): ?>
        <li>
            <a href="../router.php?action=plants&id=<?php echo $plant->id_planta; ?>">
                <?php echo $plant->nombre; ?></li>
            </a> - Precio: <?php echo $plant->precio; ?>
        </li>
        <?php endforeach; ?>
    </ul>
</body>
</html>
