<!DOCTYPE html>
<html lang="es">

<!-- head -->
<head>
    <meta charset="UTF-8">
    <base href="<?php echo BASE_URL ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="stylesheet" href="css/style.css">
    <title>Titulo</title>
</head>
<body>

<ul class="navbar-nav">
     <?php foreach($categories as $category): ?>
        <li>
                
             <a href="category/<?php echo $category->id_pedido;?>">
             <?php echo $category->id_pedido;?>
             - fecha: 
             <?php echo $category->fecha_pedido; ?> 
             -Estado:
            <?php echo $category->estado; ?>
            -Total:
            <?php echo $category->total; ?>
            </a>
            <a href="deleteCategory/<?= $category->id_pedido ?>" type="button" class='btn btn-danger btn-sm ml-auto'>Borrar</a>
            <a href="showUpdateCategory/<?= $category->id_pedido ?>" type="button" class='btn btn-danger btn-sm ml-auto'>Editar</a>
        </li>
    <?php endforeach; ?>
</ul>
<?php require 'templates/form.category.phtml' ?>
</body>
</html>