<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Plantas</title>
</head>
<body>
    <h1>Detalles de la Planta</h1>
    <h2><?=$plant->nombre ?></h2>
    <p>Precio: <?= $plant->precio ?></p>
    <p>Stock: <?= $plant->stock ?>
    <p>Pedido: <?= $pedido->estado?></p>  

    <a href="<?php echo BASE_URL; ?>plants">Volver a la lista de plantas</a> <!-- Un enlace para volver a la lista -->
</body>
</html>