<?php require_once './templates/layout/header.phtml' ?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Vivero</title>
</head>
<body>
    <h1>Lista de Plantas</h1>
    <ul>
        <?php foreach ($plants as $plant): ?>
        <li>
            <a href="plant/<?php echo $plant->id_planta; ?>">
                <?php echo $plant->nombre; ?></li>
            </a> - Precio: <?php echo $plant->precio; ?>
            <a href="<?= BASE_URL . 'deletePlant/' . $plant->id_planta ?>" type="button">Borrar</a>
            <a href="<?= BASE_URL . 'updateForm/' . $plant->id_planta ?>" type="button">Editar</a>
            
        </li>
        <?php endforeach; ?>
    </ul>
    <a href="<?php echo BASE_URL; ?>addForm">Agregar una planta</a>
</body>
</html>
<?php require './templates/layout/footer.phtml'?>