<!DOCTYPE html>
<html lang="es">

<!-- head -->
<head>
    <meta charset="UTF-8">
    <base href="<?php echo BASE_URL ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="stylesheet" href="css/style.css">
    <title>Vivero</title>
</head>
<body>


    <header>
        <nav class="navbar navbar-expand-lg bg-light">
            <div class="container-fluid">
                <a class="navbar-brand fw-bold text-success" href="">TUDAI -🌱 Vivero</a>
              
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav ms-auto">
                        <li class="nav-item">
                            <a class="nav-link text-success" href="<?= BASE_URL ?>">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-success" href="<?= BASE_URL ?>list">Pedidos</a>
                        </li>

                        <?php if (!isset($_SESSION['id'])): ?>
                            <li class="nav-item">
                            
                            <a class="nav-link text-success" href="<?= BASE_URL; ?>logout">Logout</a>
                        </li>
                        <?php endif; ?>
                        
                    </ul>
                </div>
            </div>
            </nav>
    </header>

    <main class="container mt-3">
